name: 'Content Sentiment Analysis'
description: 'Wait a designated number of milliseconds'
inputs:
  files:  # glob pattern for files
    description: 'Glob pattern for files to be checked.'
    required: true
    default: '["*.js"]'
runs:
  using: 'node12'
  main: 'dist/index.js'
