name: 'Content Sentiment Analysis'
description: 'Wait a designated number of milliseconds'
inputs:
  token:  # id of input
    description: 'Access token used to fetch the repository. The token allows the action to run authenticated Git commands.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
