name: "sentiment-analysis"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - name: "Run tests"
      run: npm test    
      env:
        CI: true
        key: ${{ secrets.GCP_KEY }} 

  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Run sentiment analysis on HTML files"
      uses: bogdaaamn/copy-sentiment-analysis@v0.6.1
      with: 
        gcp_key: ${{ secrets.GCP_KEY }} 

