name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'v*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bogdaaamn/copy-sentiment-analysis@v0.5.0

